### ISSUE TITLE
HTTP_REFERER?

### ISSUE THREAD

**Issue by kwinata** [jasonsebastian/su-entry-task#10]
https://github.com/jasonsebastian/su-entry-task/blob/43da69ece61fd08993d42dfb54bd3953a165640f/blogs/views.py#L134-L138

ini rada pertanyaan sih: kenapa perlu pake ini ya?

**Comment by jasonsebastian** [comment]
yang ini udah dibantu revisi ama jagun, jadinya pake messages framework hehehe

[https://docs.djangoproject.com/en/2.1/ref/contrib/messages/](url)
