### ISSUE TITLE
Fields of Post model comment

### ISSUE THREAD

**Issue by kwinata** [jasonsebastian/su-entry-task#2]
https://github.com/jasonsebastian/su-entry-task/blob/43da69ece61fd08993d42dfb54bd3953a165640f/blogs/models.py#L6-L9

post_id (primary key) ga usah tambahin, django otomatis buatkan buat kita primary key nya.
post_title ga necessarily unique=true, tpi kalo lu emang mau nya implemen yg unique=true ya boleh juga.
post_content, dripada bkin max_length=2500, pake django TextField aja, di formsnya juga bagus, jadi multiline form
timestamp boleh diganti namanya jadi yg lebih descriptive, misal 'date_added' atau 'added' aja

trus ini jg common practice, name field nya ga usah include nama modelnya lagi, misal kan nama model nya itu udah Post, field nya ga usah lagi 'post_content', bisa 'content' aja

taro def __str__ practice yg bagus 💯 

class Meta ordering, bagus 👍 , tapi tergantung, kadang kalo orderingnya ga perlu, bisa di ommit, karena ordering itu increase workload db process nya.

**Comment by jasonsebastian** [comment]
noted! code gw udah messed up kev hahaha jadi yg ini keknya gw ga ganti lagi
