### ISSUE TITLE
Merge view & HttpResponse(200)

### ISSUE THREAD

**Issue by kwinata** [jasonsebastian/su-entry-task#9]
https://github.com/jasonsebastian/su-entry-task/blob/43da69ece61fd08993d42dfb54bd3953a165640f/blogs/views.py#L77-L84

kan ada view comment, lu bisa merge jadi nya yg atas itu if method=='GET', trus yg add_comment itu klo method=='POST', jadi lebih rapi

Trus instead of HttpResponseRedirect, bisa response 200 OK aja, supaya user tetap di page itu.

**Comment by jasonsebastian** [comment]
gw tadi coba response 200 OK, tapi keknya ttp mesti render context deh kev jadi mesti redirect i guess?

**Comment by kwinata** [comment]
kalo mau render context kynya bisa di HttpResponse jg deh, ky mirip JSON response gitu tpi versi DjangoTemplate.
Gw lupa sih bisa atau ngga haha
